package com.example.LibraryManagement.Service;

import com.example.LibraryManagement.Entities.LibraryCard;
import com.example.LibraryManagement.Entities.Student;
import com.example.LibraryManagement.Enums.CardStatus;
import com.example.LibraryManagement.Repository.CardRepository;
import com.example.LibraryManagement.Repository.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.Optional;

@Service
public class CardService {

    @Autowired
    private CardRepository cardRepository;

    @Autowired
    private StudentRepository studentRepository;

    public LibraryCard generateCard(){
        //cardNo are autogenerated
        //card Status new
        LibraryCard card =new LibraryCard();
        card.setCardStatus(CardStatus.NEW);
        card =cardRepository.save(card);
        return card;

    }

    public String associateCardWithStudent(Integer studentId,Integer cardId){
        Optional<Student> optionalStudent=studentRepository.findById(studentId);
        Student student =optionalStudent.get();
        Optional<LibraryCard> optionalLibraryCard=cardRepository.findById(cardId);
        LibraryCard card =optionalLibraryCard.get();

        // setting the required attributes of library card entity
        card.setCardStatus(CardStatus.ACTIVE);
        card.setNameOnCard(student.getName());
        card.setStudent(student);

        // setting the required attributes of student entity
        student.setLibraryCard(card);

        studentRepository.save(student);
        return "Card with card Number " +cardId+" is associated student Id " +studentId;
    }
}
